name: Update actions-toolbox
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of actions-toolbox we are updating to'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          always-auth: true
          registry-url: ${{ secrets.ACTIONS_NEXUS_NPM_ENDPOINT }}
      - name: Set npm auth
        run: npm config set _auth "${{ secrets.ACTIONS_NEXUS_NPM_READ_TOKEN }}"
      - name: yarn install
        run: yarn install
      - name: Commit latest actions-toolbox
        run: |
          git config --global user.email "${{ secrets.ACTIONS_GITHUB_EMAIL }}"
          git config --global user.name "${{ secrets.ACTIONS_GITHUB_USERNAME }}"

          yarn add @wealthsimple/actions-toolbox@${{ github.event.inputs.version }}
          yarn build

          git commit --all --message "feat: update actions-toolbox to ${{ github.event.inputs.version }}"
          git push origin main

          yarn run semantic-release --branches main

          git tag --force --annotate v1 --message "The latest v1 release [skip ci]"
          git push origin v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
