name: Update actions-toolbox
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of actions-toolbox we are updating to'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          always-auth: true
          registry-url: ${{ secrets.ACTIONS_NEXUS_NPM_ENDPOINT }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.yarn.cache.outputs.cache-hit != 'true'
        run: |
          npm config set _auth "${{ secrets.ACTIONS_NEXUS_NPM_READ_TOKEN }}"
          yarn install
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch
      - run: yarn install
      - name: Commit latest actions-toolbox
        run: |
          git config --global user.email "${{ secrets.ACTIONS_GITHUB_EMAIL }}"
          git config --global user.name "${{ secrets.ACTIONS_GITHUB_USERNAME }}"

          yarn add @wealthsimple/actions-toolbox@${{ github.event.inputs.version }}
          yarn build

          git commit --all --message "feat: update actions-toolbox to ${{ github.event.inputs.version }}"
          git push origin ${{ steps.branch.outputs.name }}

          if [ "${{ steps.branch.outputs.name }}" = 'main' ]; then
            yarn run semantic-release --extends ./release/main
            git tag --force --annotate v1 --message "The latest v1 release [skip ci]"
            git push --force origin v1
          else
            yarn run semantic-release --extends ./release/branches
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
